### ISSUE TITLE
Directory support?

### ISSUE THREAD

**Issue by JoeFirebaugh** [hansl/angularjs-loader#1]
First of all, I want to thank you for a super cool angular script.  I was excited to see an attempt to have automatic resource loading.

I was curious if there was already an architected way to have the code in different directories?  For instance, I would like to have my main angular application in the root of the src tree and the controllers in deeper directories broken apart by feature.  It appears that the plugin only looks in the current directory for missing angular classes. 

Thanks,
Joe

**Comment by hansl** [comment]
So with the latest 2.1 I added a couple of ways to do that. In 0.1.0 you could use dots to specify directories (so my.module.file would become my/module/file.js), but that wasn't good enough for my own project. I added configuration options for this. You can specify these by using angular.loader.config().  I'll document the whole thing.

You can technically use slashes in the module names btw, so you could do just that too.
