### ISSUE TITLE
Add default to use when running wiredep tasks

### ISSUE THREAD

**Issue by iamdash** [hansl/angularjs-loader#2]
Great component, but how are we able to add the `app` attribute to the script tag when running `wiredep` tasks? I have made some updates and would like to make a pull request using `app` as the default.

**Comment by hansl** [comment]
You can set `noinit` to `true` in the tag itself, and then use `angular.loader.init({})` to initialize the component from JavaScript. That's basically how I do it for tests.

I'm always open to pull requests too, so go ahead and I'll review :)
